### ISSUE TITLE
Release, version & Nix(OS) packaging

### ISSUE THREAD

**Issue by superherointj** [jrhouston/tfk8s#12]
I've just packaged tfk8s (0.1.0) for Nix(OS).
https://github.com/NixOS/nixpkgs/pull/115544

Current Nix package is using the version number from GitHub release tag.

I plan updating NixOS package whenever a new release happens. But only for releases.
Would be nice if there were releases - even minor - when changes happened because tracking 'master' is frowned upon.

**Comment by jrhouston** [comment]
Thanks for opening this @superherointj – I'll cut a release with the correct version shortly.

**Comment by superherointj** [comment]
Thank you. 
I'll promptly keep tfk8s new releases at sync in NixOS whenever you release the software.
One day give NixOS a try, it's very nice. :-)

**Comment by jrhouston** [comment]
The v0.1.2 tag should reflect what's in the `main` branch now. 👍
