### ISSUE TITLE
Sample demo on README.md does not match.

### ISSUE THREAD

**Issue by superherointj** [jrhouston/tfk8s#23]
Sample demo on README.md does not match:

`tfk8s -f input.yaml -o output.tf`

will generate
`resource "kubernetes_manifest" "configmap_test" {`

instead of
`resource "kubernetes_manifest_hcl" "configmap_test" {`

What is the intended output?

I have removed "_hcl" when [adding a test to tfk8s package](https://github.com/NixOS/nixpkgs/pull/130164).

**Comment by jrhouston** [comment]
Oops you're right, the `_hcl` is not supposed to be tberr anymore. It's a holdover from an older version from the provider – I'll remove it.
