### ISSUE TITLE
Option to strip quotes around keys

### ISSUE THREAD

**Issue by lbodor** [jrhouston/tfk8s#30]
Would you consider adding an option to strip quotes around keys in the output? Is `terraform.FormatValue` responsible for the quotes?

```
re := regexp.MustCompile(`(\s*)"([^"]+)"(\s*)(=.*)`)
hcl = re.ReplaceAllString(hcl, "$1$2$3$4")
```

just before returning from `yamlToHCL` seems to work.

**Comment by jrhouston** [comment]
Yes the quotes are added by FormatValue – however I had to copy that package over to this codebase anyway, as they made that function private in the core Terraform repository. So we can change it to strip quotes [here](https://github.com/jrhouston/tfk8s/blob/main/contrib/hashicorp/terraform/format.go#L142). I'd rather do that than use a regex to strip them out.

**Comment by lbodor** [comment]
Yes, that would be better. I didn't realise that chaining `terraform.FormatValue` was an option.

**Comment by lbodor** [comment]
Thanks. Awesome work :100:
