### ISSUE TITLE
Reverse direction

### ISSUE THREAD

**Issue by icy** [jrhouston/tfk8s#6]
Hi,

the tool looks awesome. However I actually need to convert some terraform files back to yaml files. Would be great if the tool can support the reverse direction:

```
tfk8s --reverse .tf > output.yaml
```

I know it's quite a crazy thing...

Thanks a lot,

**Comment by jrhouston** [comment]
Thanks for opening this @icy. This is an interesting idea but is considerably more high effort than converting YAML to HCL. We could support this for the simplest case, but once a config start doing variable interpolations, dependencies on other resources, dynamic blocks, for loops and so on the we have to reinvent bits of terraform to actually evaluate the HCL so it can then be rendered into YAML.

For the simplest case we could assume the manifest is just a map with no additional syntactic sugar then it would be easy enough to decode the HCL and produce the corresponding YAML.

**Comment by icy** [comment]
@jrhouston Thanks for the feedbac. Do you think there is any chance Terraform itself can help? What I meant is that, your tool may be part of Terraform plugin. In the other direction, there maybe also option for Terraform can generate some yaml file to stdout instead of applying on the cluster.

My problem with terraform is its global lock state. On k8s cluster there are many objects and all of them rely on a global lock state of Terraform which is not suitable for my team work at the moment, hence I have to step back.

**Comment by jrhouston** [comment]
You're right that the provider could potentially generate the YAML. There's actually an open issue for this on the kubernetes provider repo: https://github.com/hashicorp/terraform-provider-kubernetes/issues/738

You should leave a 👍 on it if you want to see this added there.

**Comment by icy** [comment]
Thanks for the link to the ticket. I gives it a  +1 :P

I would close this issue then. Thanks for the discussion, and the great tool.
