### ISSUE TITLE
tfk8s command not found

### ISSUE THREAD

**Issue by vakkur** [jrhouston/tfk8s#7]
I have it installed on ubuntu 18 but

 sudo make install 
go install -ldflags "-X main.toolVersion=0.1.0"
go: downloading github.com/spf13/pflag v1.0.3
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/hashicorp/terraform v0.12.24
go: downloading github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f
go: downloading github.com/zclconf/go-cty v1.2.1
go: downloading github.com/hashicorp/hil v0.0.0-20190212112733-ab17b08d6590
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/bmatcuk/doublestar v1.1.5
go: downloading golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: downloading github.com/apparentlymart/go-cidr v1.0.1
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/google/uuid v1.1.1
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/hashicorp/hcl/v2 v2.3.0
go: downloading github.com/hashicorp/terraform-svchost v0.0.0-20191011084731-65d371908596
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/zclconf/go-cty-yaml v1.0.1
go: downloading github.com/apparentlymart/go-textseg v1.0.0
go: downloading golang.org/x/net v0.0.0-20191009170851-d66e71096ffb
go: downloading github.com/agext/levenshtein v1.2.2
go: downloading github.com/mitchellh/go-wordwrap v1.0.0

 tfk8s -f install.yaml -o argocdinstall.tf
tfk8s: command not found

**Comment by shutupflanders** [comment]
It seems we're missing a step in the install instructions.
The `make install` command installs it to your home directory (~/go/)

To add it to path, run the following:
```
ln -s ~/go/bin/tfk8s /usr/local/bin/tfk8s
```

This should fix the issue

**Comment by jrhouston** [comment]
Ah yep, thanks for opening this. The go bin folder needs to be in your `PATH` I will update the README with instructions.

**Comment by vakkur** [comment]
Now it works like magic, thank you all 👍
