### ISSUE TITLE
Package as a krew plugin to kubectl

### ISSUE THREAD

**Issue by briantopping** [jrhouston/tfk8s#8]
This would be great as a krew plugin... :)

Thanks for all your hard work!

**Comment by jrhouston** [comment]
I had a look at the docs for kubectl plugins, seems straightforward. Thanks for the suggestion! 😀

**Comment by jrhouston** [comment]
Ah, we are blocked on distributing via krew for macOS at least until we sort out https://github.com/jrhouston/tfk8s/issues/4.

In the mean time you can just do this if you want to use it as a kubectl plugin:

```bash
make build
cp tfk8s /usr/bin/local/kubectl-tfk8s
```

**Comment by briantopping** [comment]
Oh wow, that's great, thank you! I think the distribution aspect will be the best part of krew. I have tfk8s installed already, so it's not necessary, but maybe some others will find this information helpful. Thanks for all your hard work!!
